class Currency {
  final String code;
  final String name;
  final String symbol;
  final String flag;

  const Currency({
    required this.code,
    required this.name,
    required this.symbol,
    required this.flag,
  });

  static const Currency defaultCurrency = Currency(
    code: 'USD',
    name: 'United States Dollar',
    symbol: '\$',
    flag: '🇺🇸',
  );

  static const List<Currency> popularCurrencies = [
    Currency(code: 'USD', name: 'US Dollar', symbol: '\$', flag: '🇺🇸'),
    Currency(code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', flag: '🇱🇰'),
    Currency(code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺'),
    Currency(code: 'GBP', name: 'British Pound', symbol: '£', flag: '🇬🇧'),
    Currency(code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳'),
    Currency(code: 'AED', name: 'UAE Dirham', symbol: 'AED', flag: '🇦🇪'),
    Currency(code: 'CAD', name: 'Canadian Dollar', symbol: 'CA\$', flag: '🇨🇦'),
    Currency(code: 'AUD', name: 'Australian Dollar', symbol: 'AU\$', flag: '🇦🇺'),
    Currency(code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵'),
    Currency(code: 'SGD', name: 'Singapore Dollar', symbol: 'S\$', flag: '🇸🇬'),
    Currency(code: 'USDT', name: 'Tether (Crypto)', symbol: '₮', flag: '🪙'),
  ];

  static const List<Currency> allCurrencies = [
    Currency(code: 'USD', name: 'United States Dollar', symbol: '\$', flag: '🇺🇸'),
    Currency(code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', flag: '🇱🇰'),
    Currency(code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺'),
    Currency(code: 'GBP', name: 'British Pound', symbol: '£', flag: '🇬🇧'),
    Currency(code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳'),
    Currency(code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'AED', flag: '🇦🇪'),
    Currency(code: 'AFN', name: 'Afghan Afghani', symbol: '؋', flag: '🇦🇫'),
    Currency(code: 'ALL', name: 'Albanian Lek', symbol: 'L', flag: '🇦🇱'),
    Currency(code: 'AMD', name: 'Armenian Dram', symbol: '֏', flag: '🇦🇲'),
    Currency(code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', flag: '🇨🇼'),
    Currency(code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', flag: '🇦🇴'),
    Currency(code: 'ARS', name: 'Argentine Peso', symbol: '\$', flag: '🇦🇷'),
    Currency(code: 'AUD', name: 'Australian Dollar', symbol: 'AU\$', flag: '🇦🇺'),
    Currency(code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', flag: '🇦🇼'),
    Currency(code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', flag: '🇦🇿'),
    Currency(code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', flag: '🇧🇦'),
    Currency(code: 'BBD', name: 'Barbadian Dollar', symbol: '\$', flag: '🇧🇧'),
    Currency(code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', flag: '🇧🇩'),
    Currency(code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', flag: '🇧🇬'),
    Currency(code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD', flag: '🇧🇭'),
    Currency(code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', flag: '🇧🇮'),
    Currency(code: 'BMD', name: 'Bermudan Dollar', symbol: '\$', flag: '🇧🇲'),
    Currency(code: 'BND', name: 'Brunei Dollar', symbol: '\$', flag: '🇧🇳'),
    Currency(code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', flag: '🇧🇴'),
    Currency(code: 'BRL', name: 'Brazilian Real', symbol: 'R\$', flag: '🇧🇷'),
    Currency(code: 'BSD', name: 'Bahamian Dollar', symbol: '\$', flag: '🇧🇸'),
    Currency(code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', flag: '🇧🇹'),
    Currency(code: 'BWP', name: 'Botswanan Pula', symbol: 'P', flag: '🇧🇼'),
    Currency(code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', flag: '🇧🇾'),
    Currency(code: 'BZD', name: 'Belize Dollar', symbol: 'BZ\$', flag: '🇧🇿'),
    Currency(code: 'CAD', name: 'Canadian Dollar', symbol: 'CA\$', flag: '🇨🇦'),
    Currency(code: 'CDF', name: 'Congolese Franc', symbol: 'FC', flag: '🇨🇩'),
    Currency(code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', flag: '🇨🇭'),
    Currency(code: 'CLP', name: 'Chilean Peso', symbol: '\$', flag: '🇨🇱'),
    Currency(code: 'CNY', name: 'Chinese Yuan', symbol: '¥', flag: '🇨🇳'),
    Currency(code: 'COP', name: 'Colombian Peso', symbol: '\$', flag: '🇨🇴'),
    Currency(code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', flag: '🇨🇷'),
    Currency(code: 'CUP', name: 'Cuban Peso', symbol: '\$', flag: '🇨🇺'),
    Currency(code: 'CVE', name: 'Cape Verdean Escudo', symbol: '\$', flag: '🇨🇻'),
    Currency(code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', flag: '🇨🇿'),
    Currency(code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', flag: '🇩🇯'),
    Currency(code: 'DKK', name: 'Danish Krone', symbol: 'kr', flag: '🇩🇰'),
    Currency(code: 'DOP', name: 'Dominican Peso', symbol: 'RD\$', flag: '🇩🇴'),
    Currency(code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', flag: '🇩🇿'),
    Currency(code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', flag: '🇪🇬'),
    Currency(code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', flag: '🇪🇷'),
    Currency(code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', flag: '🇪🇹'),
    Currency(code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ\$', flag: '🇫🇯'),
    Currency(code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', flag: '🇫🇰'),
    Currency(code: 'GEL', name: 'Georgian Lari', symbol: '₾', flag: '🇬🇪'),
    Currency(code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', flag: '🇬🇭'),
    Currency(code: 'GIP', name: 'Gibraltar Pound', symbol: '£', flag: '🇬🇮'),
    Currency(code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', flag: '🇬🇲'),
    Currency(code: 'GNF', name: 'Guinean Franc', symbol: 'FG', flag: '🇬🇳'),
    Currency(code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', flag: '🇬🇹'),
    Currency(code: 'GYD', name: 'Guyanaese Dollar', symbol: 'GY\$', flag: '🇬🇾'),
    Currency(code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK\$', flag: '🇭🇰'),
    Currency(code: 'HNL', name: 'Honduran Lempira', symbol: 'L', flag: '🇭🇳'),
    Currency(code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', flag: '🇭🇷'),
    Currency(code: 'HTG', name: 'Haitian Gourde', symbol: 'G', flag: '🇭🇹'),
    Currency(code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', flag: '🇭🇺'),
    Currency(code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', flag: '🇮🇩'),
    Currency(code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', flag: '🇮🇱'),
    Currency(code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', flag: '🇮🇶'),
    Currency(code: 'IRR', name: 'Iranian Rial', symbol: '﷼', flag: '🇮🇷'),
    Currency(code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', flag: '🇮🇸'),
    Currency(code: 'JMD', name: 'Jamaican Dollar', symbol: 'J\$', flag: '🇯🇲'),
    Currency(code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', flag: '🇯🇴'),
    Currency(code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵'),
    Currency(code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', flag: '🇰🇪'),
    Currency(code: 'KGS', name: 'Kyrgystani Som', symbol: 'сом', flag: '🇰🇬'),
    Currency(code: 'KHR', name: 'Cambodian Riel', symbol: '៛', flag: '🇰🇭'),
    Currency(code: 'KMF', name: 'Comorian Franc', symbol: 'CF', flag: '🇰🇲'),
    Currency(code: 'KPW', name: 'North Korean Won', symbol: '₩', flag: '🇰🇵'),
    Currency(code: 'KRW', name: 'South Korean Won', symbol: '₩', flag: '🇰🇷'),
    Currency(code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD', flag: '🇰🇼'),
    Currency(code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'CI\$', flag: '🇰🇾'),
    Currency(code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', flag: '🇰🇿'),
    Currency(code: 'LAK', name: 'Laotian Kip', symbol: '₭', flag: '🇱🇦'),
    Currency(code: 'LBP', name: 'Lebanese Pound', symbol: 'L£', flag: '🇱🇧'),
    Currency(code: 'LRD', name: 'Liberian Dollar', symbol: 'L\$', flag: '🇱🇷'),
    Currency(code: 'LSL', name: 'Lesotho Loti', symbol: 'M', flag: '🇱🇸'),
    Currency(code: 'LYD', name: 'Libyan Dinar', symbol: 'LD', flag: '🇱🇾'),
    Currency(code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', flag: '🇲🇦'),
    Currency(code: 'MDL', name: 'Moldovan Leu', symbol: 'lei', flag: '🇲🇩'),
    Currency(code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', flag: '🇲🇬'),
    Currency(code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', flag: '🇲🇰'),
    Currency(code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', flag: '🇲🇲'),
    Currency(code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', flag: '🇲🇳'),
    Currency(code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP\$', flag: '🇲🇴'),
    Currency(code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', flag: '🇲🇷'),
    Currency(code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', flag: '🇲🇺'),
    Currency(code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', flag: '🇲🇻'),
    Currency(code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', flag: '🇲🇼'),
    Currency(code: 'MXN', name: 'Mexican Peso', symbol: 'Mex\$', flag: '🇲🇽'),
    Currency(code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', flag: '🇲🇾'),
    Currency(code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', flag: '🇲🇿'),
    Currency(code: 'NAD', name: 'Namibian Dollar', symbol: 'N\$', flag: '🇳🇦'),
    Currency(code: 'NGN', name: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬'),
    Currency(code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C\$', flag: '🇳🇮'),
    Currency(code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', flag: '🇳🇴'),
    Currency(code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', flag: '🇳🇵'),
    Currency(code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ\$', flag: '🇳🇿'),
    Currency(code: 'OMR', name: 'Omani Rial', symbol: 'OMR', flag: '🇴🇲'),
    Currency(code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', flag: '🇵🇦'),
    Currency(code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.', flag: '🇵🇪'),
    Currency(code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', flag: '🇵🇬'),
    Currency(code: 'PHP', name: 'Philippine Peso', symbol: '₱', flag: '🇵🇭'),
    Currency(code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', flag: '🇵🇰'),
    Currency(code: 'PLN', name: 'Polish Zloty', symbol: 'zł', flag: '🇵🇱'),
    Currency(code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', flag: '🇵🇾'),
    Currency(code: 'QAR', name: 'Qatari Rial', symbol: 'QR', flag: '🇶🇦'),
    Currency(code: 'RON', name: 'Romanian Leu', symbol: 'lei', flag: '🇷🇴'),
    Currency(code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', flag: '🇷🇸'),
    Currency(code: 'RUB', name: 'Russian Ruble', symbol: '₽', flag: '🇷🇺'),
    Currency(code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', flag: '🇷🇼'),
    Currency(code: 'SAR', name: 'Saudi Riyal', symbol: 'SR', flag: '🇸🇦'),
    Currency(code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI\$', flag: '🇸🇧'),
    Currency(code: 'SCR', name: 'Seychellois Rupee', symbol: 'SR', flag: '🇸🇨'),
    Currency(code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG', flag: '🇸🇩'),
    Currency(code: 'SEK', name: 'Swedish Krona', symbol: 'kr', flag: '🇸🇪'),
    Currency(code: 'SGD', name: 'Singapore Dollar', symbol: 'S\$', flag: '🇸🇬'),
    Currency(code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', flag: '🇸🇱'),
    Currency(code: 'SOS', name: 'Somali Shilling', symbol: 'Ssh', flag: '🇸🇴'),
    Currency(code: 'SRD', name: 'Surinamese Dollar', symbol: 'Sr\$', flag: '🇸🇷'),
    Currency(code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'Db', flag: '🇸🇹'),
    Currency(code: 'SYP', name: 'Syrian Pound', symbol: '£S', flag: '🇸🇾'),
    Currency(code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', flag: '🇸🇿'),
    Currency(code: 'THB', name: 'Thai Baht', symbol: '฿', flag: '🇹🇭'),
    Currency(code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', flag: '🇹🇯'),
    Currency(code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', flag: '🇹🇲'),
    Currency(code: 'TND', name: 'Tunisian Dinar', symbol: 'DT', flag: '🇹🇳'),
    Currency(code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T\$', flag: '🇹🇴'),
    Currency(code: 'TRY', name: 'Turkish Lira', symbol: '₺', flag: '🇹🇷'),
    Currency(code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: 'TT\$', flag: '🇹🇹'),
    Currency(code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT\$', flag: '🇹🇼'),
    Currency(code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', flag: '🇹🇿'),
    Currency(code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', flag: '🇺🇦'),
    Currency(code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', flag: '🇺🇬'),
    Currency(code: 'UYU', name: 'Uruguayan Peso', symbol: '\$U', flag: '🇺🇾'),
    Currency(code: 'UZS', name: 'Uzbekistani Som', symbol: 'soʻm', flag: '🇺🇿'),
    Currency(code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.S', flag: '🇻🇪'),
    Currency(code: 'VND', name: 'Vietnamese Dong', symbol: '₫', flag: '🇻🇳'),
    Currency(code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', flag: '🇻🇺'),
    Currency(code: 'WST', name: 'Samoan Tala', symbol: 'WS\$', flag: '🇼🇸'),
    Currency(code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', flag: '🇨🇲'),
    Currency(code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC\$', flag: '🇦🇬'),
    Currency(code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', flag: '🇸🇳'),
    Currency(code: 'XPF', name: 'CFP Franc', symbol: 'CFPF', flag: '🇵🇫'),
    Currency(code: 'YER', name: 'Yemeni Rial', symbol: 'YR', flag: '🇾🇪'),
    Currency(code: 'ZAR', name: 'South African Rand', symbol: 'R', flag: '🇿🇦'),
    Currency(code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', flag: '🇿🇲'),
    Currency(code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z\$', flag: '🇿🇼'),
    Currency(code: 'USDT', name: 'Tether (Crypto)', symbol: '₮', flag: '🪙'),
    Currency(code: 'BTC', name: 'Bitcoin (Crypto)', symbol: '₿', flag: '🪙'),
    Currency(code: 'ETH', name: 'Ethereum (Crypto)', symbol: 'Ξ', flag: '🪙'),
  ];

  static Currency getByCode(String? code) {
    if (code == null || code.isEmpty) return defaultCurrency;
    final upper = code.trim().toUpperCase();
    return allCurrencies.firstWhere(
      (c) => c.code == upper,
      orElse: () => Currency(code: upper, name: upper, symbol: upper, flag: '🌐'),
    );
  }
}
